### ISSUE TITLE
Can not reproduce your results on COCOstuff27 undet ViT/16

### ISSUE THREAD

**Issue by hnczgytmp** [hynnsk/PPAP#1]
Thank you for your insightful work!
When I run your command on an NVIDIA 3090:
`python run.py --opt ./json/server/cocostuff.json --debug`
I got the following results:
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/a46aa9a1-81d6-4dee-a3c3-d1c43860c4d5">
The Acc is ok, but the mIoU is far behind the results reported (23.95 vs 26.5) in your paper. Could you help me analyze the reason? 
By the way, I generate the crop image using the stego codebas, I just wonder whether the generation process depend on the random seed or not?

**Comment by hynnsk** [comment]
Hello,

Thank you for your interest in our work.

When I run the code with an NVIDIA RTX A6000 GPU,
The results are as:

![Github-issue](https://github.com/user-attachments/assets/1a3e2edd-1ca6-4d11-b384-b92821533b74)

I think the differences in the results may be caused by the difference in settings.

Our settings are as:
```
torch==1.10.2+cu111
torchaudio==0.8.1
torchmetrics==0.8.2
torchvision==0.9.1+cu111
pydensecrf==1.0rc3
```

And in my opinion, fivecrop does not depend on the random seed.

Thank you.

**Comment by hnczgytmp** [comment]
I have tried to rebuild my env based on your provided package, but I encounter the following problems:

```
ERROR: Cannot install torch==1.10.2+cu111 and torchvision==0.9.1+cu111 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.10.2+cu111
    torchvision 0.9.1+cu111 depends on torch==1.8.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
How do you avoid this conflict?

**Comment by hynnsk** [comment]
please try one of the following two:
```
1. torch==1.10.2 torchvision==0.11.3

2. torch==1.8.1 torchvision==0.9.1
```

**Comment by hnczgytmp** [comment]
Could you tell me which environment you have used for [your provided results](https://github.com/hynnsk/PPAP/issues/1#issuecomment-2270527763)?
Is `torch==1.10.2 torchvision==0.11.3 ` or ` torch==1.8.1 torchvision==0.9.1` ?

**Comment by hynnsk** [comment]
As mentioned above, our environment is set up with `torch==1.10.2 torchvision==0.9.1`.

![Github-issue2](https://github.com/user-attachments/assets/7a58197c-34ab-46e3-819d-1f9e8439023b)

So I'm not sure why the conflict occurs, as I constructed these settings over two years ago.

But, in my experience, the torch version is more likely to affect reproducibility. So I recommend trying `torch==1.10.2`.

**Comment by hnczgytmp** [comment]
I have tried `torch==1.10.2 torchvision==0.11.3`, the final results are:
```
[after CRF] Cluster_mIoU : 23.95
[after CRF] Cluster_Accuracy : 62.19
[after CRF] Linear_mIoU : 42.67
[after CRF] Linear_Accuracy : 75.54
```
The environment file is 
[ppap_v1.yaml.zip](https://github.com/user-attachments/files/16538598/ppap_v1.yaml.zip)

I have also tried `torch==1.8.1 torchvision==0.9.1`, the final results are:
```
[after CRF] Cluster_mIoU : 24.32
[after CRF] Cluster_Accuracy : 57.80
[after CRF] Linear_mIoU : 42.03
[after CRF] Linear_Accuracy : 75.05
```
The environment file is 
[PPAP_v2.yaml.zip](https://github.com/user-attachments/files/16538605/PPAP_v2.yaml.zip)

Both are much lower than the results reported in the paper :
Cluster_mIoU : 26.5
Cluster_Accuracy : 62.9
Linear_mIoU : 43.3
Linear_Accuracy : 76.0
