### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by yasserben** [hynnsk/PPAP#2]
Hi ! 

Can you please share with us the `environment.yml` file used to create the conda environment ?

Thank you !

**Comment by hynnsk** [comment]
Hello,

I attached a file containing all the packages installed in my environment.
It may contain packages that are not used in this project.

Thank you

[requirements_all.txt](https://github.com/user-attachments/files/16530001/requirements_all.txt)

**Comment by hnczgytmp** [comment]
I encounter the following problem:
`ERROR: Could not find a version that satisfies the requirement torch==1.10.2+cu111 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for torch==1.10.2+cu111`
Would you be able to upload your experimental environment, established under Anaconda (usually in "~/anaconda3/envs/" folder), as a compressed package to Google Cloud Disk? This would enable us to directly conduct experiments within your environment.
Thank you!

**Comment by hynnsk** [comment]
@hnczgytmp 

I can provide you with a Docker image as I didn't use anaconda environment for this project.

`docker pull gustjrdl95/ppap:latest`

You can run it directly without having to enter a conda environment.

I hope this works..!

Thank you
